# Generated by Django 4.2.5 on 2024-09-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearbuy_app', '0006_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
