# Generated by Django 4.2.5 on 2024-09-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0007_alter_vendor_point_of_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
