# Generated by Django 4.2.5 on 2024-09-09 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0005_remove_dealers_user_dealers_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('vendor_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], max_length=50)),
                ('point_of_contact', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendor_logos/')),
                ('account_holder_name', models.CharField(default='', max_length=255)),
                ('bank_name', models.CharField(default='', max_length=255)),
                ('branch', models.CharField(default='', max_length=255)),
                ('account_number', models.CharField(default='', max_length=20)),
                ('ifsc_code', models.CharField(default='', max_length=11)),
                ('terms', models.TextField()),
                ('uname', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('cpassword', models.CharField(max_length=128)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='dealers',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deal_app.vendor'),
        ),
    ]
