# Generated by Django 4.2.5 on 2024-09-10 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_vendor_alter_customuser_role'),
        ('deal_app', '0006_vendor_alter_dealers_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.user'),
        ),
    ]
